= 适配器独立仿真使用说明

== 文件目录结构

----
.
├── log							# 仿真运行时的日志目录
├── adapter -> lib/main.bin		# 主程序的符号链接
├── config
│   └── main.yaml				# 配置文件，无配置文件时会使用默认配置
└── lib
    ├── main.bin				# 主程序
	└── *						# 相关依赖
----

== 运行环境

默认 `debian:12` 容器镜像即可 (`glibc >= 2.34`)，无其它依赖。
如果容器运行遇到字符编码问题，可声明环境变量: `export LC_ALL=C.UTF-8`

== 运行仿真

----
# 查阅命令帮助
./adapter -h

# 以仿真模式运行 (不加参数时默认真机运行，依赖真机环境的 sros)
./adapter --mock -v --log-dir ./log
----

== 配置文件

由于仿真运行涉及与环境交互，部分外部信息需要手动通过配置文件提供给仿真程序，
当前涉及：货架位置，充电桩，初始位置，电池状态等

程序启动时，会按顺序搜索加载配置文件: `config/main.yaml`, `/etc/sros/main.yaml`

接入现场仿真，主要涉及以下配置参数修改:

. rcs 服务器地址和端口: `network.server_ip`, `network.server_port`
. 本地绑定端口号: `network.local_port` (`0` 随机绑定端口，进程声明周期内绑定不变，用于单机多实例运行)
. 小车 id: `main.nickname` (字符串类型，但 rcs 协议中需要这个 id 是有效的 int 类型数字)
. 货架尺寸: `rack.max_contour_length`, `rack.max_contour_width` (货架长宽，单位 mm)
. 设备类型: `device_type` (当前仿真的设备类型，目前支持顶升，辊筒，SMT，具体参考配置文件说明)

配置文件内定义了 `main` 和 `mock` 两种模式的默认参数，仿真使用 `mock` 定义的配置信息。
示例配置中 `mock` 复用了真机运行配置的部分信息，在此基础上进行覆盖。

其它信息可参考配置文件内的注释说明。

//- 其它 LDM 导入相关的基本配置项(暂未提供修改)：
//. 启用上下视 avc100 参数: 上视: 1720=True, 1721=True；下视: 1731=True，1732=False
//. 设置上下视二维码类型: 上视 1815: HUAWEI_SINGLE_SMALL_16，下视 1816: HUAWEI_SINGLE_LARGE_16
//. 开启二维码和slam融合功能: 236 允许slam和二维码融合, 239 开启二维码融合定位

// vi: set ts=4 :
